发布

diff --git a/src/backup-mysql b/src/backup-mysql
--- a/src/backup-mysql
+++ b/src/backup-mysql
@@ -108,6 +108,28 @@ ls_incremental()
         cd - &> /dev/null
 }
 
+incremental_var()
+{
+        if [[ -z "$(ls_full | xargs)" ]]; then
+                echo "Error: full backup does not exist"
+                exit 1
+        fi
+        
+        FULL_BACKUP=$(ls_full | tail -n 1)
+        FULL_BACKUP_PATH=${BACKUP_ROOT}/${BACKUP_DIR}/${FULL_BACKUP}
+        
+        BACKUP_BINLOG=$(grep "^\-- CHANGE MASTER TO MASTER_LOG_FILE" "$FULL_BACKUP_PATH" | awk -F\' '{ print $2 }')
+        BACKUP_POSITION=$(grep "^\-- CHANGE MASTER TO MASTER_LOG_FILE" "$FULL_BACKUP_PATH" | awk -F= '{ print $3 }' | sed "s/;$//g")
+        
+        MYSQL_BINLOG=$(mysql -u root -p${PASSWORD} -e "show master status" 2> /dev/null | grep ".[0-9]\{6\}" | awk '{ print $1 }')
+        MYSQL_POSITION=$(mysql -u root -p${PASSWORD} -e "show master status" 2> /dev/null | grep ".[0-9]\{6\}" | awk '{ print $2 }')
+        
+        if [[ -z "$MYSQL_BINLOG" ]] || [[ -z "$MYSQL_POSITION" ]] || [[ -z "$BACKUP_BINLOG" ]] || [[ -z "$BACKUP_POSITION" ]]; then
+                echo "Error: variable is empty"
+                exit 1
+        fi
+}
+
 default()
 {
         echo "backup-mysql: unrecognized option '$1'"
