发布

diff --git a/src/backup-mysql b/src/backup-mysql
--- a/src/backup-mysql
+++ b/src/backup-mysql
@@ -190,7 +190,14 @@ incremental_backup()
 # 增量恢复
 incremental_restore()
 {
-        echo "incremental_restore $1"
+        INCREMENTAL_BACKUP=$(ls_incremental | grep "^incremental-$1")
+        
+        if [[ -n "$INCREMENTAL_BACKUP" ]]; then
+                mysql -u root -p${PASSWORD} < ${BACKUP_ROOT}/${BACKUP_DIR}/${INCREMENTAL_BACKUP}
+        else
+                echo "Error: incremental backup does not exist"
+                exit 1
+        fi
 }
 
 full_backup_list()
