发布

diff --git a/src/myopt b/src/myopt
--- a/src/myopt
+++ b/src/myopt
@@ -1,34 +1,47 @@
 #!/bin/bash
+export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
+
+echoColor()      { echo -e "\e[1m\e[$3;$2m$1\e[0m"; }
+echoLine()       { echo -n $(echoColor "$1" "$2" "$3" ); }
+echoSuccess()    { echo $(echoLine "Success: " "32" "40")$(echoColor "$1" "37" "40"); }
+echoWarning()    { echo $(echoLine "Warning: " "33" "40")$(echoColor "$1" "37" "40"); }
+echoError()      { echo $(echoLine "Error: " "31" "40")$(echoColor "$1" "37" "40"); }
+displaySuccess() { echo $(echoColor "Success" "32" "40"); }
+displayError()   { echo $(echoColor "Error" "31" "40"); }
+
+if [ $(id -u) != "0" ]; then
+    echoError "must run with root"; exit 1
+fi
 
 #
 longOption()
 {
-    echo $1
+    echoColor "$1" "31" "40"
 }
 
 longArgument()
 {
-    echo $1
+    echoColor "$1" "35" "40"
 }
 
 shortOption()
 {
-    echo $1
+    echoColor "$1" "32" "40"
 }
 
 shortArgument()
 {
-    echo $1
+    echoColor "$1" "33" "40"
 }
 
 argumentEnd()
 {
-    echo $1
+    echoColor "$1" "34" "40"
 }
 
 argumentTwo()
 {
-    echo $1
+    echoColor "$1" "36" "40"
 }
 
 # 指令参数的个数：不存在、1个、2个
